import { createVuetify } from 'vuetify'
import '@mdi/font/css/materialdesignicons.css' // import Material Design Icons, use mdi-xxx
import 'vuetify/styles'
import {
  VMenu,
  VList,
  VListItem,
  VListItemTitle,
  VBtn,
  VIcon,
  VDataTable,
  VTextField,
  VTextarea,
  VCard,
  VCardItem,
  VCardTitle,
  VCardSubtitle,
  VCardText,
  VCardActions,
  VSpacer,
  VContainer,
  VRow,
  VCol,
  VDialog,
  VSelect,
  VProgressCircular,
  VRadioGroup,
  VRadio,
  VCombobox,
  VChip,
  VImg,
  VDivider,
} from 'vuetify/components'

const vuetify = createVuetify({
  components: {
    VMenu,
    VList,
    VListItem,
    VListItemTitle,
    VBtn,
    VIcon,
    VDataTable,
    VTextField,
    VTextarea,
    VCard,
    VCardItem,
    VCardTitle,
    VCardSubtitle,
    VCardText,
    VCardActions,
    VSpacer,
    VContainer,
    VRow,
    VCol,
    VDialog,
    VSelect,
    VProgressCircular,
    VRadioGroup,
    VRadio,
    VCombobox,
    VChip,
    VImg,
    VDivider,
  },
})

export default vuetify
